"""empty message

Revision ID: 7a7788b81ec2
Revises: f55f451fa0e6
Create Date: 2025-04-13 22:13:07.597429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a7788b81ec2'
down_revision = 'f55f451fa0e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 